# Generated by Django 5.2.14 on 2026-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionrecord',
            old_name='source',
            new_name='source_type',
        ),
        migrations.RenameField(
            model_name='emissionrecord',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='original_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='source_name',
            field=models.CharField(default='Unknown Source', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('FLAGGED', 'FLAGGED')], default='PENDING', max_length=20),
        ),
    ]
