# Generated by Django 5.2.14 on 2026-05-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_rename_source_emissionrecord_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='organization',
            field=models.CharField(default='Demo Enterprise', max_length=100),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='scope_category',
            field=models.CharField(choices=[('SCOPE_1', 'SCOPE_1'), ('SCOPE_2', 'SCOPE_2'), ('SCOPE_3', 'SCOPE_3')], default='SCOPE_1', max_length=20),
        ),
    ]
